# Map definitions
#
#   ▓▓ = wall
#   go = gopher start
#   pl = player start
#
maps:
  simple-1: |
    ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
    ▓▓  go          ▓▓
    ▓▓  ▓▓▓▓  ▓▓▓▓  ▓▓
    ▓▓  ▓▓▓▓  ▓▓▓▓  ▓▓
    ▓▓      pl      ▓▓
    ▓▓  ▓▓▓▓  ▓▓▓▓  ▓▓
    ▓▓  ▓▓▓▓  ▓▓▓▓  ▓▓
    ▓▓              ▓▓
    ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
