name: Unit tests and linting

on: [push]

jobs:
  staticcheck:
    name: Run staticcheck
    runs-on: ubuntu-latest
    steps:
      - name: staticcheck
        run: |
          # add executables installed with go get to PATH
          # TODO: this will hopefully be fixed by
          # https://github.com/actions/setup-go/issues/14
          export PATH=${PATH}:`go env GOPATH`/bin
          go get -u honnef.co/go/tools/cmd/staticcheck
          staticcheck ./...

  test:
    strategy:
      matrix:
        go: ['1.11', '1.12', '1.13', '1.14']
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    name: Go ${{ matrix.go }} [${{ matrix.platform }}]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Setup go
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go }}
      - name: Run tests
        run: go test ./... -cover
